# Generated by Django 6.0 on 2025-12-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_role_loginhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                    ("user", "User"),
                ],
                max_length=230,
            ),
        ),
    ]
