# Generated by Django 6.0 on 2025-12-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="total_questions",
        ),
        migrations.AlterField(
            model_name="test",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="time_limit",
            field=models.IntegerField(default=60),
        ),
    ]
