# Generated by Django 6.0 on 2026-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='class_level',
            field=models.CharField(default='No Class', max_length=280),
        ),
    ]
