# Generated by Django 6.0 on 2025-12-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers_users2_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="date_added",
            field=models.DateField(auto_now=True),
        ),
    ]
